input {
  beats {
    port => 5044
  }
}

filter {
  if "_dateparsefailure" in [tags] {
    mutate {
      remove_tag => ["_dateparsefailure"]
    }
  }
  mutate {
    add_field => { "processed_by" => "logstash" }
    add_field => { "index_time" => "%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "crawler-logs-%{+YYYY.MM.dd}"
    data_stream => "false"
  }
}